title: My Data Science Projects ğŸ¦‰ 
date: 2020-07-05
header_pages:
  - index.md
  
author: tuttoaposto ğŸ¦‰
# email: your-email@domain.com
description: |  # The following block of text will be the entire value for description
  This site shows the data science projects I did using Jupyter Notebook.
      
  About me: I am a data analyst from the San Francisco Bay Area. Love salsa dancing ğŸ’ƒ and running ğŸƒâ€â™€ï¸.
   
image: https://github.com/tuttoaposto/OpenSource/blob/master/DBS_Westie_1280.jpg
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  tuttoaposto

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
  plugins:
    - jekyll-seo-tag
