title: Tuttoaposto's Data Science Projects
author: tuttoaposto
# email: your-email@domain.com
description: This site shows the data science projects I did using Jupyter Notebook.


# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  tuttoaposto

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
